model:
  architecture: resnet18
  channels: 3
  target_classes: 10

train_parameters:
  lr: 1e-3
  batch_size: 100
  n_epochs: 200
  max_accuracy: 0.99
  is_reset: true

active_learning:
  strategy: badge
  budget: 1000
  rounds: 15
  initial_points: 1000

  strategy_args:
    batch_size : 64
    lr: 0.01

dataset:
  name: cifar10
  download_path: /home/nakatsuka/dataset/cifar10

logger:
  name: mlflow
  args:
    uri: http://192.168.1.236:45000/
    experiment_name: dal